In [1]:
from mxnet import * 
from mxnet.gluon import nn
npx.set_np()


In [6]:
def pool2d(X, pool_size, mode= 'max'):
    p_h, p_w = pool_size
    Y = np.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            
            if mode == 'max':
                Y[i , j] = np.max(X[i: i + p_h, j: j + p_w])
            
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [7]:
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
pool2d(X, (2,2))

array([[4., 5.],
       [7., 8.]])

In [8]:
pool2d(X, (2,2), 'avg')

array([[2., 3.],
       [5., 6.]])

In [9]:
X = np.arange(16).reshape(1,1,4,4)
X

array([[[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]]])

In [10]:
pool2d = nn.MaxPool2D(3)
pool2d(X)

array([[[[10.]]]])

In [12]:
pool2d = nn.MaxPool2D(3, padding= 1, strides= 2)
pool2d(X)

array([[[[ 5.,  7.],
         [13., 15.]]]])

In [13]:
pool2d = nn.MaxPool2D((2,3), padding=(1,2), strides=(2,3))
pool2d(X)

array([[[[ 0.,  3.],
         [ 8., 11.],
         [12., 15.]]]])

In [14]:
X = np.concatenate((X, X + 1), axis= 1)
X


array([[[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]]])

In [15]:
pool2d = nn.MaxPool2D(3, padding= 1, strides= 2)
pool2d(X)


array([[[[ 5.,  7.],
         [13., 15.]],

        [[ 6.,  8.],
         [14., 16.]]]])