In [1]:
from mxnet import *
from mxnet.gluon import nn
npx.set_np()

npx.cpu(0), npx.gpu(), npx.gpu(1)

(cpu(0), gpu(0), gpu(1))

In [2]:
npx.num_gpus()

0

In [3]:
def try_gpu(i = 0 ):
    return npx.gpu(i) if npx.num_gpus() >= i+1 else npx.cpu()

In [4]:
def try_all_gpus():
    ctxes = [npx.gpu(i) for i in range(npx.num_gpus())]
    return ctxes if ctxes else [npx.cpu()]

In [5]:
try_gpu(), try_gpu(3), try_all_gpus()

(cpu(0), cpu(0), [cpu(0)])

In [6]:
x = np.array([1, 2, 3])
x

array([1., 2., 3.])

In [7]:
x.ctx

cpu(0)

In [8]:
x = np.ones((2,3), ctx=try_gpu())

In [9]:
y = np.random.uniform(size= (2, 3), ctx= try_gpu(1))
y

array([[0.5488135 , 0.5928446 , 0.71518934],
       [0.84426576, 0.60276335, 0.8579456 ]])

### COPYING

In [10]:
z = x.copyto(try_gpu(1))
print(x)
print(z)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
y+z

array([[1.5488136, 1.5928446, 1.7151893],
       [1.8442657, 1.6027634, 1.8579457]])

In [13]:
z = x.as_in_ctx(try_gpu(1))
z

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
y.as_in_ctx(try_gpu(1)) is y

True

In [15]:
y.copyto(try_gpu(1)) is y

False

### GLUON AND GPU

In [16]:
net = nn.Sequential()
net.add(nn.Dense(1))
net.initialize(ctx= try_gpu())

In [18]:
net(x)

array([[0.04421056],
       [0.04421056]])

In [20]:
net[0].weight.data()

array([[ 0.00628365,  0.04861524, -0.01068833]])