## PARAMETER MANAGEMENT

In [1]:
import time 
start = time.time()
from mxnet import init, np, npx
from mxnet.gluon import nn
npx.set_np()
end = time.time()
print('sure: %f' %(end - start))

sure: 1.603889


In [1]:
import time 
start = time.time()
from mxnet import *
from mxnet.gluon import nn
npx.set_np()
end = time.time()
print('sure: %f' %(end - start))

sure: 1.534556


In [2]:
net = nn.Sequential()
net.add(nn.Dense(256, activation= 'relu'))
net.add(nn.Dense(10))
net.initialize()

In [3]:
x = np.random.uniform(size= (2, 20))
net(x)

array([[ 0.06240272, -0.03268593,  0.02582653,  0.02254182, -0.03728798,
        -0.04253786,  0.00540613, -0.01364186, -0.09915452, -0.02272738],
       [ 0.02816677, -0.03341204,  0.03565666,  0.02506382, -0.04136416,
        -0.04941845,  0.01738528,  0.01081961, -0.09932579, -0.01176298]])

In [4]:
print(net[0].params)
print(net[1].params)

dense0_ (
  Parameter dense0_weight (shape=(256, 20), dtype=float32)
  Parameter dense0_bias (shape=(256,), dtype=float32)
)
dense1_ (
  Parameter dense1_weight (shape=(10, 256), dtype=float32)
  Parameter dense1_bias (shape=(10,), dtype=float32)
)


In [5]:
print(net[1].bias)
print(net[1].bias.data())

Parameter dense1_bias (shape=(10,), dtype=float32)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
print(net[0].params['dense0_weight'])
print(net[0].params['dense0_weight'].data())

Parameter dense0_weight (shape=(256, 20), dtype=float32)
[[ 0.06700657 -0.00369488  0.0418822  ... -0.05517294 -0.01194733
  -0.00369594]
 [-0.03296221 -0.04391347  0.03839272 ...  0.05636378  0.02545484
  -0.007007  ]
 [-0.0196689   0.01582889 -0.00881553 ...  0.01509629 -0.01908049
  -0.02449339]
 ...
 [-0.02055008 -0.02618652  0.06762936 ... -0.02315108 -0.06794678
  -0.04618235]
 [ 0.02802853  0.06672969  0.05018687 ... -0.02206502 -0.01315478
  -0.03791244]
 [-0.00638592  0.00914261  0.06667828 ... -0.00800052  0.03406764
  -0.03954004]]


In [9]:
net[0].weight.grad()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
print(net[0].collect_params())
print(net.collect_params())

dense0_ (
  Parameter dense0_weight (shape=(256, 20), dtype=float32)
  Parameter dense0_bias (shape=(256,), dtype=float32)
)
sequential0_ (
  Parameter dense0_weight (shape=(256, 20), dtype=float32)
  Parameter dense0_bias (shape=(256,), dtype=float32)
  Parameter dense1_weight (shape=(10, 256), dtype=float32)
  Parameter dense1_bias (shape=(10,), dtype=float32)
)


In [15]:
net.collect_params()['dense0_bias'].data()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [16]:
print(net.collect_params('.*weight'))
print(net.collect_params('dense0.*'))


sequential0_ (
  Parameter dense0_weight (shape=(256, 20), dtype=float32)
  Parameter dense1_weight (shape=(10, 256), dtype=float32)
)
sequential0_ (
  Parameter dense0_weight (shape=(256, 20), dtype=float32)
  Parameter dense0_bias (shape=(256,), dtype=float32)
)


## COLLECT PARAMS NESTED BLOCKS

In [17]:
def block1():
    net = nn.Sequential()
    net.add(nn.Dense(32, activation= 'relu'))
    net.add(nn.Dense(16, activation= 'relu'))
    return net

def block2():
    net = nn.Sequential()
    for i in range(4):
        net.add(block1())
    return net

rgnet = nn.Sequential()
rgnet.add(block2())
rgnet.add(nn.Dense(10))
rgnet.initialize()
rgnet(x)

array([[-4.1923025e-09,  1.9830502e-09,  8.9444063e-10,  6.2912990e-09,
        -3.3241778e-09,  5.4330038e-09,  1.6013515e-09, -3.7408681e-09,
         8.5468477e-09, -6.4805539e-09],
       [-3.7507064e-09,  1.4866974e-09,  6.8314709e-10,  5.6925784e-09,
        -2.6349172e-09,  4.8626667e-09,  1.4280275e-09, -3.4603027e-09,
         7.4127922e-09, -5.7896132e-09]])

In [18]:
print(rgnet.collect_params)
print(rgnet.collect_params())

<bound method Block.collect_params of Sequential(
  (0): Sequential(
    (0): Sequential(
      (0): Dense(20 -> 32, Activation(relu))
      (1): Dense(32 -> 16, Activation(relu))
    )
    (1): Sequential(
      (0): Dense(16 -> 32, Activation(relu))
      (1): Dense(32 -> 16, Activation(relu))
    )
    (2): Sequential(
      (0): Dense(16 -> 32, Activation(relu))
      (1): Dense(32 -> 16, Activation(relu))
    )
    (3): Sequential(
      (0): Dense(16 -> 32, Activation(relu))
      (1): Dense(32 -> 16, Activation(relu))
    )
  )
  (1): Dense(16 -> 10, linear)
)>
sequential1_ (
  Parameter dense2_weight (shape=(32, 20), dtype=float32)
  Parameter dense2_bias (shape=(32,), dtype=float32)
  Parameter dense3_weight (shape=(16, 32), dtype=float32)
  Parameter dense3_bias (shape=(16,), dtype=float32)
  Parameter dense4_weight (shape=(32, 16), dtype=float32)
  Parameter dense4_bias (shape=(32,), dtype=float32)
  Parameter dense5_weight (shape=(16, 32), dtype=float32)
  Parameter dense5_

In [20]:
rgnet[0][1][0].bias.data()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
rgnet[0][1][0].weight.data()

array([[-0.06668283, -0.05615795,  0.03207945,  0.06233052, -0.04007202,
        -0.03620897,  0.05832634,  0.01770394,  0.02265018,  0.02730031,
        -0.03029332, -0.02373442, -0.0334728 , -0.06132633, -0.04613291,
         0.02485522],
       [ 0.04226188, -0.05293959, -0.00861325, -0.0656759 , -0.03122761,
         0.03458199,  0.06339473, -0.05448471,  0.04231372,  0.04356337,
         0.01208242,  0.06847104,  0.04234281, -0.01348437, -0.05318226,
         0.02044314],
       [ 0.02410293,  0.06019162, -0.02461878,  0.0583655 ,  0.02625126,
        -0.02620089,  0.06463199, -0.06619769,  0.03925034, -0.02971543,
         0.00917824, -0.04397712,  0.03437465, -0.0201811 , -0.00443356,
        -0.03022658],
       [-0.03080768,  0.04802642, -0.06431124,  0.00342479,  0.02480843,
        -0.0518848 , -0.0500372 , -0.01599217, -0.00569128,  0.02323274,
         0.02334563,  0.05361784,  0.05478116, -0.005434  ,  0.01531091,
         0.05854053],
       [-0.03951854,  0.04148562, -0

## PARAMETER INITIALIZATION

In [22]:
net.initialize(init= init.Normal(sigma= 0.01), force_reinit= True)
net[0].weight.data()[0]

array([ 5.3957910e-03, -9.8788990e-03, -7.4317548e-03, -7.0842844e-03,
        6.4959102e-03, -1.4880487e-02,  1.8743128e-02, -8.2659340e-03,
        1.4534276e-03,  1.6201856e-02,  1.5926106e-02,  2.2331162e-03,
       -8.8592555e-05, -1.2915777e-02, -7.2338693e-03, -1.7293985e-03,
       -4.9947016e-03,  8.7698260e-03,  2.0079103e-03, -9.6906107e-03])

In [23]:
net.initialize(init= init.Constant(1), force_reinit= True)
net[0].weight.data()[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [24]:
net[0].initialize(init= init.Xavier(), force_reinit= True)
net[1].initialize(init= init.Constant(42), force_reinit= True)

print(net[0].weight.data()[0])
print(net[1].weight.data()[0, 0])

[-0.06319056 -0.10960881  0.11757872 -0.07595599 -0.0849717   0.0851637
  0.08330765  0.04028694 -0.0305525   0.02012795 -0.03856885  0.1375024
  0.10155623 -0.05016676 -0.02575382 -0.14205234  0.14225402  0.02719662
 -0.0888046  -0.00962897]
42.0


In [26]:
class Myinit(init.Initializer):
    def _init_weight(self, name, data):
        print('init', name, data.shape)
        data[:] = np.random.uniform(-10, 10, data.shape)
        data *= np.abs(data) >= 5

net.initialize(Myinit(), force_reinit= True)
net[0].weight.data()[0]

init dense0_weight (256, 20)
init dense1_weight (10, 256)


array([-5.172625 , -7.0209026,  5.1446533, -9.844563 ,  8.545956 ,
       -0.       ,  0.       , -0.       ,  5.107664 ,  9.658335 ,
        5.8564453,  7.4483128,  0.       ,  0.       , -0.       ,
        7.9034443,  0.       ,  5.4223766,  8.5655575,  5.1224785])

In [27]:
net[0].weight.data()[:] += 1
net[0].weight.data()[0, 0] = 42
net[0].weight.data()[0]

array([42.       , -6.0209026,  6.1446533, -8.844563 ,  9.545956 ,
        1.       ,  1.       ,  1.       ,  6.107664 , 10.658335 ,
        6.8564453,  8.448313 ,  1.       ,  1.       ,  1.       ,
        8.903444 ,  1.       ,  6.4223766,  9.5655575,  6.1224785])

### TIED PARAMETERS

In [28]:
net = nn.Sequential()
shared = nn.Dense(8, activation= 'relu')
net.add(nn.Dense(8, activation= 'relu'),
       shared,
       nn.Dense(8, activation= 'relu', params= shared.params),
       nn.Dense(10))
net.initialize()

x = np.random.uniform(size= (2, 20))
net(x)

array([[ 1.1493918e-05, -3.7545291e-05,  2.5705798e-05, -4.1792186e-06,
         1.3921880e-05,  1.0111785e-05,  3.1895048e-05,  5.9858639e-06,
        -5.0634389e-05,  3.2276825e-05],
       [ 6.7366571e-05, -7.8969111e-05,  7.3926378e-05,  6.7717170e-05,
         7.5913667e-05,  2.6337137e-05,  5.5379642e-05,  3.6538037e-05,
        -9.0345595e-05,  4.0183393e-05]])

In [29]:
print(net[1].weight.data()[0] == net[2].weight.data()[0])
net[1].weight.data()[0, 0] = 100

print(net[1].weight.data()[0] == net[2].weight.data()[0])

[ True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True]
